---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4


platforms:
  - name: centos-6.6
  #- name: centos-5.10

suites:
- name: default
  run_list:
    - "recipe[pdb_motd]"
